### ISSUE TITLE
Creación de la Pantalla de Perfil del Jugador

### ISSUE THREAD

**Issue by fran1017** [UNIZAR-30226-2022-01/proyecto_software_frontend_react#1]

**Comment by Guilleuz** [comment]
Implementación incial en 4c7d6720fe099ab5668644c4b62eb2bf046712fd.

**Comment by Guilleuz** [comment]
Añadido botón para enviar solicitud desde el perfil de un usuario y opción para cambiar la biografía desde tu propio perfil.
c8bc456595f536a210d1269fa7b6f5b0cbc8793c
