### ISSUE TITLE
Diseño e Implementación de la Ventana de Ranking

### ISSUE THREAD

**Issue by fran1017** [UNIZAR-30226-2022-01/proyecto_software_frontend_react#11]

**Comment by Guilleuz** [comment]
Implementada en 43d10d3034d8ef071dbb6cc1ebd35ce0d67751e8.
Permite consultar el perfil de los usuarios que aparecen en el ranking y destaca la posición del usuario.
Se puede cambiar el número de usuarios a mostrar modificando manualmente el estado.
