### ISSUE TITLE
Implementación y diseño de los Amigos del usuario

### ISSUE THREAD

**Issue by fran1017** [UNIZAR-30226-2022-01/proyecto_software_frontend_react#17]

**Comment by Guilleuz** [comment]
Implementada pantalla de lista de amigos en 568079f3ab24e69c374b1830d07f09be65fb24fc.
Permite ver el perfil de los amigos y eliminarlos de la lista.
Permite también buscar usuarios por nombre, ver su perfil y enviarles una solicitud de amistad.
