### ISSUE TITLE
Diseño e Implementación de la Tienda

### ISSUE THREAD

**Issue by fran1017** [UNIZAR-30226-2022-01/proyecto_software_frontend_react#9]

**Comment by Guilleuz** [comment]
Implementada en 769b7b9ac9a93129ad040b3b4830daa0192f1593.

**Comment by Guilleuz** [comment]
Al actualizar la pantalla después de realizar una compra, no se actualizan correctamente los objetos que tiene el usuario.
Comprobando con logs el estado se actualiza correctamente pero no se renderiza bien.

**Comment by Guilleuz** [comment]
Problema solucionado en c35120369bb3bfc73ef4c9cbda09c4be6bf91cc3.
